name: world-hello 

on: push  #trigger

jobs:
  world-hello-job:
  
    runs-on: ubuntu-latest #runner

    steps: #steps to perfrom actions
      -name: checkout repository  code
       uses: actions/checkout@v4
      -run: echo "$(cat hello_world.txt)"
    
